### ISSUE TITLE
Tricore

### ISSUE THREAD

**Issue by brandonros** [mephi42/libtcg#1]
What would need to be done to include support for the Tricore target/hardware from QEMU?

**Comment by mephi42** [comment]
When I implemented this for S/390, I had to follow the logic in `vl.c` and take only the absolutely necessary pieces. For Tricore, I think that at least the `S390CPU` handling bits in `main()`, `libtcg_init()`, `libtcg_gen()`, `llvm_init()`, `llvm_pc()` and `llvm_init_globals()` need to be replaced. All the other code should be ok as is, modulo bugs, of course. Unfortunately I did not think of making arch support modular here, since it was for a single very specific use case.
